image: python:3.9-buster

before_script:
  - apt-get update -y
  - pip install -r requirements.txt

test:
  stage: test
  script:
  - make test
  - mkdir test
  - mv public test/$CI_COMMIT_BRANCH
  artifacts:
    paths:
    - test
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - make build
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
