site_name: DIRAC Project 
site_url: https://diracgrid.org/
site_description: Homepage of the DIRAC Project documentation
site_author: Andrei Tsaregorodtsev
docs_dir: '.'   
site_dir: '../public' 
use_directory_urls: false

# Theming
theme:
  name: material
  language: en
#  custom_dir: 'overrides/' 
  logo: assets/images/Dirac_logo_black-white-negative.png
  favicon: assets/images/Dirac_favicon_logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
  icon:
    admonition:
      info: octicons/info-16

extra_css:
  - assets/stylesheets/dirac.css      

# Content
nav:
  - Home: dirac.md
  - Code: code.md
  - Documentation: documentation.md
  - Users: users.md
  - Events: events.md
  - Consortium: consortium.md
  - Contacts: contacts.md

extra:
  homepage: ../index.html

# Plugins
plugins:
  - search
copyright: Copyright &copy; DIRAC Consortium – Maintained by Andrei Tsaregorodtsev

# Mkdocs material extensions
# https://squidfunk.github.io/mkdocs-material/extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

